name: LiteLoaderQQNT-Plugin-Brevity-btn Plugin Release

on:
    pull_request:
        branches:
            - 'main'
        types:
            - closed

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Zip the Build
              run: zip -r LiteLoaderQQNT-Plugin-Brevity-btn.zip ./

            - name: Commit SHA
              run: echo ${{github.sha}} > Release.txt

            - name: Test
              run: cat Release.txt

            - name: Create Release and Upload Release Asset
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: |
                      LiteLoaderQQNT-Plugin-Brevity-btn.zip
                      Release.txt
