name: LiteLoaderQQNT-Plugin-Brevity-btn  Release

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: "Build & test"
        run: |
          echo "done!"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.RELEASES_TOKEN }}"
          automatic_release_tag: "test"
          prerelease: true
          title: "预构建版本"
